// Editor-only match driver. On the website, React owns the clock and streams
// sampled entity states into the bridge buffer. Inside the Unity Editor there
// is no website — so this component loads the baked sample match from
// unity/SampleData (generated by `npm run unity:sample` in the repo root),
// samples the dense tracks in C#, and writes through the exact same buffer.
// Press Play in the editor and a real match runs while you tweak lighting,
// post-processing and assets.

using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace Pitchside
{
    public class EditorMatchSource : MonoBehaviour
    {
        public MatchBridge bridge;

        [Header("Editor playback")]
        public bool autoPlay = true;
        [Tooltip("Playback speed multiplier.")]
        public float speed = 1f;
        [Tooltip("Jump to this match-clock time (seconds) on Play. 0 = kickoff.")]
        public float startAt = 60f;

        [Header("Runtime (read-only)")]
        public float clock;
        public float duration;

        Track[] tracks;
        bool active;

        void Start()
        {
#if UNITY_EDITOR
            var dir = Path.GetFullPath(Path.Combine(Application.dataPath, "..", "SampleData"));
            var setupPath = Path.Combine(dir, "sample-setup.json");
            var tracksPath = Path.Combine(dir, "sample-tracks.bin");
            if (!File.Exists(setupPath) || !File.Exists(tracksPath))
            {
                Debug.LogWarning(
                    "[Pitchside] No sample match found. Run `npm run unity:sample` in the repo root " +
                    "to bake one for editor preview (looked in " + dir + ").");
                return;
            }

            var setup = JsonUtility.FromJson<MatchSetupMsg>(File.ReadAllText(setupPath));
            if (setup == null || setup.entities.Length == 0)
            {
                Debug.LogError("[Pitchside] sample-setup.json could not be parsed.");
                return;
            }

            if (bridge == null) bridge = GetComponent<MatchBridge>();
            bridge.ApplySetup(setup);

            var byId = LoadTracks(tracksPath);
            int n = Mathf.Min(setup.entities.Length, MatchBridge.MaxEntities);
            tracks = new Track[n];
            for (int i = 0; i < n; i++)
                byId.TryGetValue(setup.entities[i].id, out tracks[i]);

            duration = setup.duration;
            clock = Mathf.Clamp(startAt, 0, duration);
            active = true;
            Debug.Log($"[Pitchside] Sample match loaded: {setup.teams[0].name} vs {setup.teams[1].name}, " +
                      $"{n} entities, {duration / 60f:0.0} min.");
#endif
        }

        void Update()
        {
#if UNITY_EDITOR
            if (!active) return;
            if (autoPlay)
            {
                clock = Mathf.Repeat(clock + Time.deltaTime * speed, duration);
            }
            bridge.WriteClock(clock, autoPlay);

            var s = new TrackSample();
            for (int i = 0; i < tracks.Length; i++)
            {
                var tr = tracks[i];
                if (tr == null)
                {
                    bridge.WriteEntityState(i, 0, 0, 0, 0, 0, 0, false);
                    continue;
                }
                tr.Sample(clock, ref s);
                bridge.WriteEntityState(i, s.x, s.y, s.z, s.heading, s.speed, s.action, true);
            }
#endif
        }

        // binary layout (little-endian, written by scripts/export-unity-sample.ts):
        // [count:i32] then per track [idLen:i32][id utf8][hz:f32][t0:f32][n:i32]
        // [x,y,z,speed,heading: f32×n each][action: u8×n]
        static Dictionary<string, Track> LoadTracks(string path)
        {
            var byId = new Dictionary<string, Track>();
            using var br = new BinaryReader(File.OpenRead(path));
            int trackCount = br.ReadInt32();
            for (int k = 0; k < trackCount; k++)
            {
                int idLen = br.ReadInt32();
                string id = Encoding.UTF8.GetString(br.ReadBytes(idLen));
                var t = new Track
                {
                    hz = br.ReadSingle(),
                    t0 = br.ReadSingle(),
                    count = br.ReadInt32(),
                };
                t.x = ReadFloats(br, t.count);
                t.y = ReadFloats(br, t.count);
                t.z = ReadFloats(br, t.count);
                t.speed = ReadFloats(br, t.count);
                t.heading = ReadFloats(br, t.count);
                t.action = br.ReadBytes(t.count);
                byId[id] = t;
            }
            return byId;
        }

        static float[] ReadFloats(BinaryReader br, int count)
        {
            var bytes = br.ReadBytes(count * 4);
            var floats = new float[count];
            System.Buffer.BlockCopy(bytes, 0, floats, 0, bytes.Length);
            return floats;
        }
    }
}
